name: Eleventy Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies & build
        run: |
          npm ci
      - run: npx @11ty/eleventy
      # - name: Deploy
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    publish_dir: ./dist
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # Send Github page to sparna.fr
      - name: SFTP Transfer
        uses: danhendrickson/sftp-transfer-action@v2023.51.2
        with:
          # Server name secret
          server: ${{ secrets.SERVER }}
          # Username secret
          user: ${{ secrets.USER }}
          # Password secret
          pass: ${{ secrets.PASSWORD }}
          # Port
          port: 22
          # Local Path
          local-path: ./dist
          # Remote Path
          remote-path: ${{ secrets.REMOTE_PATH }}
