name: Eleventy Build
on:
  push:
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # - name: Build
      #  uses: TartanLlama/actions-eleventy@master
      #  with:
      #    install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
