name: Eleventy Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
     # - uses: actions/checkout@master
      #  with:
      #    ref: main
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies & build
        run: |
          npm ci

      #- run: npm run build
      #- name: Build
      #  uses: TartanLlama/actions-eleventy@master
      #  with:
      #    install_dependencies: true
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
